// Error codes
export enum ErrorCodes {
  UNAVAILABLE_ID = 1,
  WRONG_PASSWORD,
  WRONG_REGISTER_DATA,
  VALIDATE_FAILED,

  ERROR_GETTING_AUDIO = 10,
  ERROR_DOWNLOADING_AUDIO,
  ERROR_AUDIO_JSON_PARSE,
  NO_SEARCHED_AUDIO,

  ERROR_RESPONSE_FROM_NLP = 20,
  NO_KEYWORDS_FROM_NLP,

  ERROR_SEARCHING_VIDEO = 30,
  NO_SEARCHED_VIDEOS,
  ERROR_DOWNLOADING_VIDEO,
  ERROR_GETTING_LICENSED_VIDEO,
  WRONG_INDEXED_VIDEO,

  ERROR_GENERATING_SUBTITLE = 40,

  ERROR_ENCODING = 50,
}
